# Generated by Django 4.0.3 on 2022-04-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Message Title.', max_length=125)),
                ('message', models.TextField(help_text='What is on your mind...')),
            ],
        ),
    ]
