# Generated by Django 4.0.3 on 2022-04-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_employee_delete_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
